export type Service = {
  id: string,
  user_id: string,
  store_id: string,
  category_id: number,
  supplier_id: number,
  sku: string,
  name: string,
  short_name: string,
  description: string | null,
  unit_type: number,
  supply_price: string,
  cost_price: string,
  unit_price: string,
  deductible_amount: number,
  deductible_amount_type: number,
  allow_alt_description: boolean,
  featured_image: string | null,
  ordering: number,
  points: number,
  number_turn: number,
  red_time: number,
  yellow_time: number,
  delay_time: number,
  finish_time: number,
  bg_color: string,
  font_color: string,
  published: number,
  created_by?: string | null,
  updated_by?: string | null,
  created_at?: string,
  updated_at?: string,
  deleted_at?: string | null
};
